= Demo Jakarta

This module is used to prepare the samples to demonstrate at the classroom.

== Setup
=== Project

Create project or add module Jakarta EE, using Gradle and Java. Select `Jakarta EE 10` with Web Profile and Eclipse Link (ORM).

If you are using JDK 21 currently, it is necessary to update the Gradle wrapper.
[source,shell]
gradle wrapper

Remove the following lines from the Gradle build script. Unfortately Gradle signals a error if we specify the JDK compatbility to 21.
[source,groovy]
sourceCompatibility = '21'
targetCompatibility = '21'

Add useful dependencies to the Gradle build script.
[source,groovy]
compileOnly 'org.projectlombok:lombok:1.18.30'
annotationProcessor 'org.projectlombok:lombok:1.18.30'
implementation 'org.apache.commons:commons-lang3:3.13.0'

=== Glassfish

Download Glassfish under https://glassfish.org/download or using Homebrew under macOS to install it. Add the GLASSFISH_HOME environment to startup profile.
[source,shell]
brew install glassfish
export GLASSFISH_HOME=/opt/homebrew/opt/glassfish/libexec

Check if `domain2` is already created and running. If not create it. We are creating a own domain, because the default one, `domain1` using the Port 8080 which may give some problems.
[source,shell]
----
asadmin list-domains
asadmin create-domain --instanceport 8082 --adminport 4852 domain2
asadmin start-domain domain2
----

In the above command the domain server is started in the background. In the development phase it may useful to start the domain server interactively.
[source,shll]
asadmin stop-domain domain2
asadmin start-domain -v domain2

== Hello World

Let's start with a simple Hello World application. IntelliJ generates us a simple app. Stop the manually started Glassfish domain, update the configuration and select the `domain2`.

=== Manual deployment

Instead of running the app with IntelliJ we can start the domain and deploy the War to the Auto-Deploy folder. Define a environment variable to point to the right domain deploy folder.
[source,shell]
export DEPLOYMENT_DIR=$GLASSFISH_HOME/glassfish/domains/domain2/autodeploy

We can list this folder to check if the deployment was successful (deployed). Now we build the war and copy it to the deployment folder
[source,shell]
----
asadmin start-domain domain2
gradle build
cp build/libs/demo-jakarta-1.0.war $DEPLOYMENT_DIR
ls $DEPLOYMENT_DIR
tail $GLASSFISH_HOME//glassfish/domains/domain2/logs/server.log
http :8082/demo-jakarta-1.0/
----

Under http://localhost:4852 we see also the status of the deployment.

=== Simple Greeting App

==== Configure Facelet

To configure Facelet template engine (servlet) add the following Java class to your application
[source,java]
----
@FacesConfig
@ApplicationScoped
@ApplicationPath("/api")
public class AppConfig extends Application {
    @Produces
    public Logger getLogger() {
        return Logger.getLogger("demo-jakarta");
    }
}
----

Now we are creating a simple app that ask for the name, stores this into a history table and greets the user including a list of person already logged in.
[plantuml]
----
class HelloView <<Facelets>>
class HelloBean <<Model>> {
    - <<Inject>> repository: HelloRepository
    +input: String
    +output: String
    +submit()
}
class HelloRepository <<Stateless>> {
    - <<Inject>> data: HelloData
    +findAll(): List
    +add(user: String)
}
class HelloData <<ApplicationScoped>> {
    +history: List
}
HelloView -> HelloBean
HelloBean -> HelloRepository
HelloRepository -> HelloData
----

== Database
Install and start PostgresSQL database locally and create `admin` user and `samples` database.
[source,sql]
----
create user admin with password 'admin';
create database samples owner admin;
\c samples
create schema demo authorization admin;
\dn
----

Define the DEPLOYMENT_DIR environment variable. Maybe add to your startup script.
[source,shell]
----
export DEPLOYMENT_DIR=$GLASSFISH_HOME/glassfish/domains/domain2/autodeploy
----

You may create the table through ORM or by hand
[source,sql]
----
CREATE TABLE demo.guests
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(100)                            NOT NULL,
    city    VARCHAR(100)                            NOT NULL,
    message VARCHAR(500),
    CONSTRAINT pk_guests PRIMARY KEY (id)
);

ALTER TABLE demo.guests
    ADD CONSTRAINT uc_2007b5927a613fdf6bda16f4b UNIQUE (name, city);
----
